spring.application.name=Gatekeeper
server.port=8081

#---------> DATABASE CONFIG (SqlLite) <---------------------
spring.datasource.url=jdbc:sqlite:gatekeeper.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

#-------> LOGGING ------------------------------------------------

logging.level.org.springframework.security=DEBUG